FROM golang:1.22-alpine AS builder

WORKDIR /src

# Download dependencies first (layer cache friendly).
# go.sum is generated by `go mod tidy` during setup; both files must exist.
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/ledgerlite ./cmd/server

# ── runtime image ───────────────────────────────────────────────────────────
FROM alpine:3.19

RUN apk add --no-cache ca-certificates

COPY --from=builder /bin/ledgerlite /bin/ledgerlite

EXPOSE 8080

ENTRYPOINT ["/bin/ledgerlite"]
